let () =
  Alcotest.run "gohttp"
    [
      ("Method", Test_method.tests);
      ("Status", Test_status.tests);
      ("Header", Test_header.tests);
      ("Sniff", Test_sniff.tests);
      ("Cookie", Test_cookie.tests);
      ("Transfer", Test_transfer.tests);
      ("Request", Test_request.tests);
      ("ReadRequest", Test_readrequest.tests);
      ("RequestWrite", Test_requestwrite.tests);
      ("Response", Test_response.tests);
      ("ResponseWrite", Test_responsewrite.tests);
      ("StreamRead", Test_stream_read.tests);
      ("StreamWrite", Test_stream_write.tests);
      ("StreamClient", Test_stream_client.tests);
      ("Net", Test_net.tests);
      ("Mapping", Test_mapping.tests);
      ("Pattern", Test_pattern.tests);
      ("RoutingTree", Test_routing_tree.tests);
      ("Ascii", Test_ascii.tests);
      ("Serve", Test_serve.tests);
      ("Clientserver", Test_clientserver.tests);
      ("Form", Test_request_form.tests);
      ("Context", Test_context.tests);
      ("H2", Test_h2.tests);
      ("HpackTables", Test_hpack_tables.tests);
      ("Hpack", Test_hpack.tests);
      ("H2Frame", Test_h2_frame.tests);
      ("H2Flow", Test_h2_flow.tests);
      ("H2DataBuffer", Test_h2_databuffer.tests);
      ("H2Pipe", Test_h2_pipe.tests);
      ("H2Write", Test_h2_write.tests);
      ("H2Writesched", Test_h2_writesched.tests);
      ("H2Tls", Test_h2_tls.tests);
      ("H2Server", Test_h2_server.tests);
      ("H2Transport", Test_h2_transport.tests);
      ("H2ClientServer", Test_h2_clientserver.tests);
    ]
